AWSTemplateFormatVersion: 2010-09-09
Description: Creating a custom managed policy
Resources:
  CreateTestDBPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Policy for creating a test database
      Path: "/"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "rds:CreateDBInstance"
            Resource: !Join
              - ""
              - - "arn:aws:rds:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - ":db:test*"
            Condition:
              StringEquals:
                "rds:DatabaseEngine": mysql
          - Effect: Allow
            Action: "rds:CreateDBInstance"
            Resource: !Join
              - ""
              - - "arn:aws:rds:"
                - !Ref "AWS::Region"
                - ":"
                - !Ref "AWS::AccountId"
                - ":db:test*"
            Condition:
              StringEquals:
                "rds:DatabaseClass": db.t2.micro
Outputs:
  CreateTestDBPolicy:
    Description: Policy for creating a test database
    Value: !Ref CreateTestDBPolicy
    Export:
      Name: CreateTestDBPolicy
